version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  producer:
    build: .
    command: python src/producer.py
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  consumer:
    build: .
    command: python src/consumer.py
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  dashboard:
    build: .
    command: streamlit run src/dashboard.py --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - redis
      - producer
    environment:
      - REDIS_HOST=redis